version: '3.7'
services:
  mongodb:
    image: mongo:latest
    hostname: mongo
    container_name: mongodb-test
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: testdb
    ports:
      - 27017:27017
    networks:
      - test
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
  bitapp:
    image: bit-app:latest
    hostname: bitapp
    container_name: bitapp
    ports:
      - 8080:8080
    networks:
      - test

networks:
    test:
        driver: bridge